import {expect, test} from '@playwright/test'
import path from 'node:path'
test('top menus support keyboard navigation, disabled actions and view settings', async ({page}, testInfo) => {
  await page.goto('./'); await expect(page.getByLabel('Open assembly files')).toBeEnabled()
  const file = page.getByRole('menuitem', {name: 'File', exact: true})
  const brand = page.locator('.app-menubar .app-name')
  await expect(brand).toHaveText('ILens')
  await expect(brand.locator('svg, a')).toHaveCount(0)
  const brandBounds = await brand.boundingBox(); const fileBounds = await file.boundingBox()
  expect(brandBounds!.x + brandBounds!.width).toBeLessThan(fileBounds!.x)
  await expect(page.locator('.toolbar, .brand-mark, .preview-label, .search-trigger')).toHaveCount(0)
  await file.focus(); await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('menuitem', {name: 'Open Assembly…', exact: true})).toBeFocused()
  await expect(page.getByRole('menuitem', {name: 'Export to Project…', exact: true})).toBeDisabled()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('menuitem', {name: 'Settings…', exact: true})).toBeFocused()
  await page.keyboard.press('Escape'); await expect(page.getByRole('menuitem', {name: 'Edit', exact: true})).toBeFocused()
  await page.getByRole('menuitem', {name: 'View', exact: true}).click()
  await page.getByRole('menuitemcheckbox', {name: 'Light Appearance'}).click()
  await expect(page.locator('.application')).toHaveClass(/(?:^|\s)light(?:\s|$)/)
  await page.getByRole('menuitem', {name: 'File', exact: true}).click()
  await expect(page.getByRole('menu', {name: 'File', exact: true})).toBeVisible()
  await expect(page.locator('.drop-zone')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await page.screenshot({path: testInfo.outputPath('top-menu.png'), animations: 'disabled'})
  await page.locator('h1').click(); await expect(page.getByRole('menu', {name: 'File', exact: true})).toHaveCount(0)
  await file.click()
  const picker = page.waitForEvent('filechooser')
  await page.getByRole('menuitem', {name: 'Open Assembly…', exact: true}).click()
  await (await picker).setFiles(path.resolve('samples/fixtures/ILens.Dependency.dll'))
  await expect(page.getByLabel('Primary assembly')).toHaveValue('1')
  await expect(page.locator('.menu-context')).toHaveText('ILens.Dependency.dll')
  await page.getByRole('menuitem', {name: 'Help', exact: true}).click()
  await page.getByRole('menuitem', {name: 'About ILens', exact: true}).click()
  await expect(page.getByRole('dialog', {name: 'About ILens'})).toBeVisible()
})
