import {test, expect} from '@playwright/test'
import path from 'node:path'

const fixture = (name: string) => path.resolve(`samples/fixtures/ILens.${name}.dll`)

test('editor settings change real highlighting, persist, and leave the workspace neutral', async ({page}, testInfo) => {
  const failures: string[] = []
  page.on('pageerror', error => failures.push(error.message))
  await page.goto('./')
  await expect(page.getByLabel('Open assembly files')).toBeEnabled(); await page.getByRole('menuitem', {name: 'Edit', exact: true}).click(); await page.getByRole('menuitem', {name: 'Settings…', exact: true}).click()
  const dialog = page.getByRole('dialog', {name: 'Settings', exact: true})
  await expect(dialog).toBeVisible()
  const preview = dialog.getByLabel('Syntax theme preview')
  for (const [theme, background, keyword] of [
    ['neutral', 'rgb(10, 10, 10)', 'rgb(250, 250, 250)'],
    ['dark', 'rgb(30, 30, 30)', 'rgb(86, 156, 214)'],
    ['light', 'rgb(255, 255, 255)', 'rgb(207, 34, 46)'],
    ['monokai', 'rgb(39, 40, 34)', 'rgb(249, 38, 114)'],
    ['solarized', 'rgb(0, 43, 54)', 'rgb(181, 137, 0)'],
    ['dracula', 'rgb(40, 42, 54)', 'rgb(255, 121, 198)'],
  ]) {
    await dialog.getByLabel('Code theme').selectOption(theme)
    await expect(dialog.locator('.cm-editor')).toHaveCSS('background-color', background)
    await expect(preview.getByText('public', {exact: true})).toHaveCSS('color', keyword)
    await expect(page.locator('.application')).toHaveCSS('background-color', 'rgb(10, 10, 10)')
  }
  await dialog.getByLabel('Syntax highlighting', {exact: true}).uncheck()
  await expect(preview.locator('.cm-line').nth(1).locator('span')).toHaveCount(0)
  await dialog.getByLabel('Syntax highlighting', {exact: true}).check()
  await dialog.getByLabel('Appearance', {exact: true}).selectOption('light')
  await expect(dialog.locator('.cm-editor')).toHaveCSS('background-color', 'rgb(40, 42, 54)')
  await expect(page.locator('.application')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await dialog.getByLabel('Font size').selectOption('16')
  await dialog.getByLabel('Line numbers', {exact: true}).uncheck()
  await dialog.getByLabel('Word wrap', {exact: true}).check()
  await expect(dialog.locator('.cm-editor')).toHaveCSS('font-size', '16px')
  await expect(dialog.locator('.cm-gutters')).toHaveCount(0)
  await page.screenshot({path: testInfo.outputPath('settings-light-dracula.png'), fullPage: true})
  await dialog.getByRole('button', {name: 'Done', exact: true}).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('menuitem', {name: 'Edit', exact: true})).toBeFocused()
  await page.reload()
  await expect(page.getByLabel('Open assembly files')).toBeEnabled(); await page.getByRole('menuitem', {name: 'Edit', exact: true}).click(); await page.getByRole('menuitem', {name: 'Settings…', exact: true}).click()
  await expect(dialog.getByLabel('Code theme')).toHaveValue('dracula')
  await expect(dialog.getByLabel('Appearance', {exact: true})).toHaveValue('light')
  await expect(dialog.getByLabel('Font size')).toHaveValue('16')
  await expect(dialog.getByLabel('Line numbers', {exact: true})).not.toBeChecked()
  await expect(dialog.getByLabel('Word wrap', {exact: true})).toBeChecked()
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await page.getByLabel('Open assembly files').setInputFiles(fixture('Patterns'))
  await expect(page.getByTestId('target-framework')).toHaveText('.NET 10.0')
  await page.getByRole('menuitem', {name: 'Edit', exact: true}).click(); await page.getByRole('menuitem', {name: 'Search Assembly…', exact: true}).click()
  await page.getByLabel('Search members and strings').fill('Calculator.Sum')
  await page.getByRole('button', {name: /Sum.*Calculator.Sum/}).click()
  await expect(page.getByLabel('C# code viewer')).toContainText('for (')
  await expect(page.locator('.viewer-container .cm-editor')).toHaveCSS('background-color', 'rgb(40, 42, 54)')
  await expect(page.getByLabel('C# code viewer').getByText('for', {exact: true})).toHaveCSS('color', 'rgb(255, 121, 198)')
  await expect(page.getByRole('button', {name: 'Toggle word wrap'})).toHaveAttribute('aria-pressed', 'true')
  await page.screenshot({path: testInfo.outputPath('custom-code-theme.png'), fullPage: true})
  await page.getByRole('tab', {name: 'IL', exact: true}).click()
  await expect(page.getByLabel('IL code viewer')).toContainText('blt.s')
  await expect(page.locator('.viewer-container .cm-editor')).toHaveCSS('background-color', 'rgb(40, 42, 54)')
  await expect(page.getByLabel('Open assembly files')).toBeEnabled(); await page.getByRole('menuitem', {name: 'Edit', exact: true}).click(); await page.getByRole('menuitem', {name: 'Settings…', exact: true}).click()
  await dialog.getByRole('button', {name: 'Reset editor settings'}).click()
  await expect(dialog.getByLabel('Code theme')).toHaveValue('neutral')
  await dialog.getByRole('button', {name: 'Done', exact: true}).click()
  await expect(page.locator('.viewer-container .cm-editor')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await expect(page.locator('.viewer-container .cm-gutters')).toBeVisible()
  expect(failures).toEqual([])
})

test('framework versions and obfuscation warnings come from the selected assembly metadata', async ({page}, testInfo) => {
  const failures: string[] = []
  page.on('pageerror', error => failures.push(error.message))
  await page.goto('./')
  await expect(page.getByLabel('Open assembly files')).toBeEnabled()
  await page.getByLabel('Open assembly files').setInputFiles(fixture('Patterns'))
  await expect(page.getByTestId('target-framework')).toHaveText('.NET 10.0')
  await expect(page.getByTestId('obfuscation-status')).toHaveText('No markers found')
  await expect(page.getByRole('region', {name: 'Assembly warnings'})).toHaveCount(0)
  await page.getByLabel('Add dependency files').setInputFiles([fixture('InspectionMarkers'), fixture('NoTarget')])
  await expect(page.getByLabel('Primary assembly').locator('option')).toHaveCount(3)
  await page.getByLabel('Primary assembly').selectOption({label: 'ILens.InspectionMarkers.dll'})
  const warnings = page.getByRole('region', {name: 'Assembly warnings'})
  await expect(warnings).toContainText('Obfuscation markers detected')
  await warnings.locator('summary').click()
  for (const tool of ['ConfuserEx', 'Dotfuscator', 'Babel Obfuscator', 'SmartAssembly']) await expect(warnings.locator('summary')).toContainText(tool)
  await expect(warnings).toContainText('fixture marker')
  await expect(warnings).toContainText('not prove which tool')
  const icon = warnings.locator('.warning-icon')
  await expect(icon).toHaveCSS('color', 'rgb(248, 113, 113)')
  await expect(icon).toHaveCSS('animation-duration', '1.8s')
  await expect(warnings).toHaveCSS('background-color', 'rgb(42, 20, 23)')
  await expect(warnings.locator('.warning-details')).toHaveCSS('background-color', 'rgb(17, 28, 45)')
  await page.screenshot({path: testInfo.outputPath('obfuscation-warnings.png'), fullPage: true, animations: 'disabled'})
  await page.getByRole('menuitem', {name: 'View', exact: true}).click(); await page.getByRole('menuitemcheckbox', {name: 'Light Appearance'}).click()
  await expect(icon).toHaveCSS('color', 'rgb(220, 38, 38)')
  await expect(warnings).toHaveCSS('background-color', 'rgb(255, 241, 242)')
  await expect(warnings.locator('.warning-details')).toHaveCSS('background-color', 'rgb(239, 246, 255)')
  await page.emulateMedia({reducedMotion: 'reduce'})
  await expect(icon).toHaveCSS('animation-name', 'none')
  await page.screenshot({path: testInfo.outputPath('obfuscation-warnings-light.png'), fullPage: true})
  await warnings.getByRole('button', {name: /Inspect 0x/}).first().click()
  await expect(page.getByLabel('Metadata code viewer')).toContainText('ConfusedByAttribute')
  await page.getByLabel('Primary assembly').selectOption({label: 'ILens.NoTarget.dll'})
  await expect(page.getByTestId('target-framework')).toHaveText('Not declared')
  await expect(page.getByTestId('obfuscation-status')).toHaveText('No markers found')
  await expect(warnings).toHaveCount(0)
  expect(failures).toEqual([])
})
