import {test, expect} from '@playwright/test'
import path from 'node:path'

test('stylesheet applies the IDE layout, controls, editor and both themes', async ({page}, testInfo) => {
  const failures: string[] = []
  const cssResponses: {url: string; status: number; type: string}[] = []
  page.on('pageerror', error => failures.push(error.message))
  page.on('response', response => {
    if (/\.css(?:\?|$)/.test(response.url())) cssResponses.push({url: response.url(), status: response.status(), type: response.headers()['content-type'] ?? ''})
  })
  await page.goto('/')
  await expect(page.locator('.application')).toHaveCSS('display', 'flex')
  await expect(page.locator('.application')).toHaveCSS('background-color', 'rgb(10, 10, 10)')
  await expect(page.locator('.application')).toHaveCSS('font-family', /sans-serif/)
  await expect(page.locator('.workspace')).toHaveCSS('display', 'grid')
  await expect(page.locator('.toolbar')).toHaveCSS('height', '61px')
  await expect(page.locator('.toolbar')).toHaveCSS('display', 'flex')
  await expect(page.locator('.toolbar .open-button')).toHaveCSS('border-radius', '6px')
  const panes = await Promise.all(['.explorer-pane', '.center-pane', '.inspector-pane'].map(selector => page.locator(selector).boundingBox()))
  expect(panes.every(Boolean)).toBe(true)
  expect(panes[0]!.width).toBe(285)
  expect(panes[1]!.x).toBeGreaterThan(panes[0]!.x + panes[0]!.width)
  expect(panes[2]!.x).toBeGreaterThan(panes[1]!.x + panes[1]!.width)
  expect(panes[0]!.y).toBe(panes[2]!.y)
  expect(panes[0]!.height).toBeGreaterThan(700)
  await page.screenshot({path: testInfo.outputPath('styled-start.png'), fullPage: true})

  await expect(page.getByLabel('Open assembly files')).toBeEnabled()
 await page.getByLabel('Open assembly files').setInputFiles(path.resolve('samples/fixtures/ILens.Patterns.dll'))
  await expect(page.getByLabel('Primary assembly')).toHaveValue('1')
  await page.getByRole('button', {name: /Search assembly/}).click()
  await page.getByLabel('Search members and strings').fill('Calculator.Sum')
  await page.getByRole('button', {name: /Sum.*Calculator.Sum/}).click()
  await expect(page.getByLabel('C# code viewer')).toContainText('for (')
  await expect(page.locator('.cm-scroller')).toHaveCSS('font-family', /monospace/)
  await expect(page.locator('.cm-gutters')).toBeVisible()
  await expect(page.locator('.cm-editor')).toHaveCSS('background-color', 'rgb(10, 10, 10)')
  await page.screenshot({path: testInfo.outputPath('styled-dark-method.png'), fullPage: true})
  await page.getByRole('tab', {name: 'IL', exact: true}).click()
  await expect(page.getByLabel('IL code viewer')).toContainText('blt.s')
  await page.screenshot({path: testInfo.outputPath('styled-il.png'), fullPage: true})
  await page.getByRole('tab', {name: 'C#', exact: true}).click()
  await page.getByRole('button', {name: 'Switch color theme'}).click()
  await expect(page.locator('.application')).toHaveClass('application light')
  await expect(page.locator('.application')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await expect(page.locator('.cm-editor')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await expect(page.locator('.workspace')).toHaveCSS('display', 'grid')
  await page.screenshot({path: testInfo.outputPath('styled-light-method.png'), fullPage: true})
  expect(failures).toEqual([])
  expect(cssResponses.length).toBeGreaterThan(0)
  expect(cssResponses.every(r => r.status === 200 || r.status === 304)).toBe(true)
  expect(cssResponses.some(r => r.status === 200 && r.type.includes('text/css'))).toBe(true)
})
