'use client'
import {cn, ui} from '../lib/ui'
import {useEffect, useRef, useState} from 'react'
import {Check, Download, LoaderCircle, Plus, Redo2, Trash2, Undo2, X} from 'lucide-react'
import type {DecompilerClient} from '../lib/rpc'
import {diagnostic, tokenHex, type Diagnostic, type EditableInstruction, type EditPreview, type SearchHit} from '../lib/types'
import type {EditorSettings} from '../lib/editor-settings'
import CodeViewer from './CodeViewer'
const pageSize = 100
export default function ILEditorDialog({client, assembly, token, name, settings, theme, onClose, onExport}: {client: DecompilerClient; assembly: number; token: number; name: string; settings: EditorSettings; theme: string; onClose: () => void; onExport: () => void}) {
  const dialog = useRef<HTMLDialogElement>(null); const controller = useRef(new AbortController()); const nextId = useRef(0)
  const [snapshot, setSnapshot] = useState<EditPreview | null>(null)
  const [rows, setRows] = useState<EditableInstruction[]>([])
  const [past, setPast] = useState<EditableInstruction[][]>([]); const [future, setFuture] = useState<EditableInstruction[][]>([])
  const [opcodes, setOpcodes] = useState<[string, string][]>([])
  const [busy, setBusy] = useState(true); const [error, setError] = useState<Diagnostic | null>(null)
  const [page, setPage] = useState(0); const [preview, setPreview] = useState<'editor' | 'original' | 'validated'>('editor')
  const [query, setQuery] = useState(''); const [hits, setHits] = useState<SearchHit[]>([])
  const [message, setMessage] = useState('')
  const [targetRow, setTargetRow] = useState<string | null>(null)
  const dirty = snapshot !== null && JSON.stringify(rows) !== JSON.stringify(snapshot.instructions)
  useEffect(() => {
    const previous = document.activeElement; dialog.current?.showModal(); const abort = new AbortController(); controller.current = abort; const signal = abort.signal
    void (async () => {try {const result = await client.call('openMethodEdit', {assembly, token}, {signal}); setSnapshot(result); setRows(result.instructions); setOpcodes(await client.call('getOpcodes', {}, {signal}))} catch (error) {if (!signal.aborted) setError(diagnostic(error))} finally {if (!signal.aborted) setBusy(false)}})()
    return () => {abort.abort(); dialog.current?.close(); if (previous instanceof HTMLElement && previous.isConnected) previous.focus()}
  }, [client, assembly, token])
  useEffect(() => {
    if (!query.trim()) {setHits([]); return}
    const abort = new AbortController(); const timer = setTimeout(() => {void client.call('search', {assembly, query}, {signal: abort.signal}).then(setHits).catch(() => {})}, 250)
    return () => {clearTimeout(timer); abort.abort()}
  }, [client, assembly, query])
  function change(next: EditableInstruction[]) {setPast(previous => {const kept = [...previous, rows].slice(-40); let size = 0; return kept.reverse().filter(item => {size += JSON.stringify(item).length * 2; return size <= 8 * 1024 * 1024}).reverse()}); setFuture([]); setRows(next); setError(null); setMessage('Unvalidated changes');}
  function update(index: number, patch: Partial<EditableInstruction>) {change(rows.map((row, i) => i === index ? {...row, ...patch} : row))}
  function insert(index: number) {if (rows.length >= 10_000) return; let id: string; do {id = `new_${++nextId.current}`} while (rows.some(r => r.id === id)); change([...rows.slice(0, index), {id, opcode: 'nop', operand: ''}, ...rows.slice(index)])}
  function remove(index: number) {const id = rows[index].id; if (rows.some((r, i) => i !== index && r.operand.split(',').some(target => target.trim() === id))) {setError({code: 'invalid_edit', message: 'This instruction is a branch target.', detail: `Retarget branches and switch arms referring to ${id} before deleting it.`}); return} change(rows.filter((_, i) => i !== index)); setPage(p => Math.min(p, Math.max(0, Math.ceil((rows.length - 1) / pageSize) - 1)))}
  async function apply(discard = false) {
    if (!snapshot) return
    setBusy(true); setError(null)
    try {
      const result = discard ? await client.call('discardMethodEdit', {assembly, token, revision: snapshot.revision}, {signal: controller.current.signal}) : await client.call('applyMethodEdit', {assembly, token, revision: snapshot.revision, instructions: rows}, {signal: controller.current.signal})
      if (controller.current.signal.aborted) return
      setSnapshot(result); setRows(result.instructions); setPast([]); setFuture([]); setMessage(discard || !result.changed ? 'Original method restored.' : 'Validation passed. This change is included in modified assembly export.')
    } catch (error) {if (!controller.current.signal.aborted) setError(diagnostic(error))}
    finally {if (!controller.current.signal.aborted) setBusy(false)}
  }
  return <dialog ref={dialog} className={cn(ui.dialog, "il-editor-dialog [&[open]]:flex [&[open]]:flex-col [&[open]]:overflow-hidden [&_>_.settings-header]:shrink-0 [&_>_.settings-footer]:shrink-0 w-[min(1080px,_calc(100vw_-_40px))] max-h-[calc(100vh_-_48px)]")} aria-labelledby="il-edit-title" onCancel={e => {e.preventDefault(); onClose()}}>
    <header className={cn(ui.dialogHeader)}><div><h2 id="il-edit-title">Edit method IL</h2><p>{name} · {tokenHex(token)}</p></div><button className={cn(ui.iconButton)} aria-label="Close IL editor" onClick={onClose}><X size={18} /></button></header>
    <div className="il-edit-body [&_p]:text-muted-foreground [&_p]:text-[12px] [&_p]:leading-[1.65] [&_p]:my-2 [&_p]:mx-0 [&_p]:[overflow-wrap:anywhere] pt-0 pr-6 pb-5 pl-6 overflow-auto min-h-0">
      <p className="editor-scope">Edit supported static and instance methods, including arrays, objects and fields. Existing signatures and metadata tokens are retained. Generics, constructor bodies and exception handlers remain read-only.</p>
      {snapshot && <><div className="il-edit-toolbar flex justify-between items-center gap-3 py-3 px-0 flex-wrap"><div className="view-tabs flex items-stretch bg-muted rounded-md h-8 p-[3px] gap-0.5 [&_button]:flex [&_button]:items-center [&_button]:gap-[5px] [&_button]:bg-transparent [&_button]:text-muted-foreground [&_button]:border [&_button]:border-solid [&_button]:border-transparent [&_button]:rounded-[4px] [&_button]:text-[12px] [&_button]:py-0 [&_button]:px-2.5 [&_button.active]:text-foreground [&_button.active]:bg-background [&_button.active]:border-b-transparent [&_button.active]:shadow-[0_1px_2px_#00000014]">{(['editor', 'original', 'validated'] as const).map(v => <button key={v} className={cn(preview === v ? "active" : "")} onClick={() => setPreview(v)}>{v === 'editor' ? 'Instructions' : v === 'original' ? 'Original IL' : 'Validated IL'}</button>)}</div><div className={cn(ui.actions)}><button className={cn(ui.iconButton)} aria-label="Undo IL change" disabled={busy || !past.length} onClick={() => {setFuture(next => [rows, ...next]); setRows(past[past.length - 1]); setPast(past.slice(0, -1))}}><Undo2 size={15} /></button><button className={cn(ui.iconButton)} aria-label="Redo IL change" disabled={busy || !future.length} onClick={() => {setPast(next => [...next, rows]); setRows(future[0]); setFuture(future.slice(1))}}><Redo2 size={15} /></button><button className={cn(ui.button, ui.subtle)} disabled={busy || !dirty && !snapshot.changed} onClick={() => void apply(true)}>Discard changes</button><button className={cn(ui.button, ui.primary)} disabled={busy || !dirty} onClick={() => void apply()}>{busy ? <LoaderCircle className="spin animate-spin motion-reduce:animate-none" size={14} /> : <Check size={14} />}Validate and apply</button></div></div>
      {preview === 'editor' ? <>
        <div className="instruction-table-scroll max-h-[43vh] overflow-auto border border-solid border-border rounded-[6px]"><table className="instruction-table w-full border-collapse table-fixed text-[12px] [&_th]:sticky [&_th]:top-0 [&_th]:z-1 [&_th]:bg-muted [&_th]:text-left [&_th]:text-muted-foreground [&_th]:font-medium [&_th]:p-2.5 [&_th:first-child]:w-32.5 [&_th:nth-child(2)]:w-45 [&_th:last-child]:w-19.5 [&_td]:py-[5px] [&_td]:px-2 [&_td]:border-t [&_td]:border-solid [&_td]:border-t-border [&_input]:w-full [&_input]:bg-background [&_input]:text-foreground [&_input]:border [&_input]:border-solid [&_input]:border-border [&_input]:rounded-[4px] [&_input]:py-[7px] [&_input]:px-2 [&_input]:font-mono [&_input]:text-[12px] [&_input]:[outline:none] [&_input:focus]:border-ring [&_input:focus]:shadow-[0_0_0_1px_var(--ring)] [&_code]:text-muted-foreground [&_code]:text-[11px]"><thead><tr><th>Label</th><th>Opcode</th><th>Operand / target label</th><th>Actions</th></tr></thead><tbody>{rows.slice(page * pageSize, (page + 1) * pageSize).map((row, relative) => {const index = page * pageSize + relative; const original = snapshot.original.find(r => r.id === row.id); const changed = !original || original.opcode !== row.opcode || original.operand !== row.operand; return <tr key={row.id} className={cn(changed ? "instruction-changed bg-muted [&_td:first-child]:shadow-[inset_3px_0_0_var(--foreground)]" : "")}><td><code>{row.id}</code></td><td><input aria-label={`Opcode ${row.id}`} disabled={busy} value={row.opcode} list="il-opcodes" onChange={e => update(index, {opcode: e.target.value})} spellCheck={false} /></td><td><input aria-label={`Operand ${row.id}`} disabled={busy} value={row.operand} onFocus={() => setTargetRow(row.id)} onChange={e => update(index, {operand: e.target.value})} spellCheck={false} maxLength={65536} /></td><td><button className={cn(ui.iconButton)} title="Insert instruction before" aria-label={`Insert before ${row.id}`} disabled={busy} onClick={() => insert(index)}><Plus size={14} /></button><button className={cn(ui.iconButton)} title="Delete instruction" aria-label={`Delete ${row.id}`} disabled={busy} onClick={() => remove(index)}><Trash2 size={14} /></button></td></tr>})}</tbody></table></div>
        <datalist id="il-opcodes">{opcodes.map(([name, kind]) => <option key={name} value={name}>{kind}</option>)}</datalist>
        <div className="instruction-pagination flex items-center gap-3 py-3 px-0 text-muted-foreground text-[11px] [&_button:last-child]:ml-auto"><button className={cn(ui.button, ui.subtle)} disabled={busy || page === 0} onClick={() => setPage(p => p - 1)}>Previous</button><span>{rows.length} instructions · Page {page + 1} / {Math.max(1, Math.ceil(rows.length / pageSize))}</span><button className={cn(ui.button, ui.subtle)} disabled={busy || (page + 1) * pageSize >= rows.length} onClick={() => setPage(p => p + 1)}>Next</button><button className={cn(ui.button, ui.subtle)} disabled={busy || rows.length >= 10_000} onClick={() => {insert(rows.length); setPage(Math.floor(rows.length / pageSize))}}>Append instruction</button></div>
        <details className="token-picker [&_>_input]:w-full [&_>_input]:bg-background [&_>_input]:text-foreground [&_>_input]:border [&_>_input]:border-solid [&_>_input]:border-border [&_>_input]:rounded-[4px] [&_>_input]:py-[7px] [&_>_input]:px-2 [&_>_input]:font-mono [&_>_input]:text-[12px] [&_>_input]:[outline:none] [&_>_input:focus]:border-ring [&_>_input:focus]:shadow-[0_0_0_1px_var(--ring)] border-t border-solid border-t-border pt-3 text-[12px] [&_summary]:cursor-pointer [&_summary]:mb-3 [&_summary]:text-muted-foreground [&_>_div]:max-h-37.5 [&_>_div]:overflow-auto"><summary>Find an existing metadata token</summary><input aria-label="Find IL operand token" placeholder="Search methods or strings…" value={query} maxLength={256} onChange={e => setQuery(e.target.value)} /><p>Focus an operand, then select a token to insert it. Call signatures are checked during validation.</p><div>{hits.slice(0, 30).map((hit, i) => <button className="token-link hover:text-foreground bg-transparent border-0 flex items-center gap-[7px] text-left text-muted-foreground w-full py-1.5 px-0 text-[11px] [&>span]:flex-1 [&>span]:overflow-hidden [&>span]:text-ellipsis [&>span]:whitespace-nowrap [&>code]:text-faint [&>code]:font-mono [&>code]:text-[9px] [&>code]:font-normal [&>code]:leading-normal [&>svg]:shrink-0" key={`${hit.token}-${i}`} disabled={busy || !targetRow} onClick={() => {const index = rows.findIndex(r => r.id === targetRow); if (index >= 0) update(index, {operand: tokenHex(hit.token)})}}><span>{hit.name}</span><code>{tokenHex(hit.token)}</code></button>)}</div></details>
      </> : <div className="edit-code-preview h-95 overflow-hidden border border-solid border-border rounded-[6px]"><CodeViewer label={preview === 'original' ? 'Original method IL' : 'Validated method IL'} text={preview === 'original' ? snapshot.original.map(r => `${r.id}: ${r.opcode} ${r.operand}`).join('\n') : snapshot.il} language="IL" settings={settings} theme={theme} /></div>}</>}
      {busy && !snapshot && <p role="status">Opening editable method…</p>}{message && <p role="status">{message}</p>}{error && <div className="export-warning border border-solid border-warning-border text-warning-foreground bg-warning-background p-3 rounded-[6px] text-[12px] [overflow-wrap:anywhere] [&_p]:text-inherit [&_p]:mb-0" role="alert"><strong>{error.code === 'unsupported_edit' ? 'This method cannot be edited yet.' : error.message}</strong><p>{error.detail}</p></div>}
    </div>
    <footer className={cn(ui.dialogFooter)}><span className="export-footnote self-center text-[11px] text-muted-foreground max-w-[60%] leading-[1.5]">{dirty ? 'Unvalidated edits are discarded when this editor closes.' : snapshot?.changed ? 'Validated changes are kept until the workspace closes.' : 'The original assembly bytes are preserved.'}</span><button className={cn(ui.button, ui.primary)} disabled={busy || dirty || !snapshot?.changed} onClick={onExport}><Download size={14} />Export modified assembly</button></footer>
  </dialog>
}
