// Derived from dotnet/runtime opcode.def. Copyright .NET Foundation and contributors.
// MIT license; see docs/third-party-notices.md. Encoded opcode reference: ECMA-335 Partition III.
use crate::cil::{Flow, Op, OperandKind};
pub fn opcode(value: u16) -> Option<Op> {
    Some(match value {
        0x0000 => Op {
            name: "nop",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 0,
        },
        0x0001 => Op {
            name: "break",
            operand: OperandKind::InlineNone,
            flow: Flow::Break,
            pop: 0,
            push: 0,
        },
        0x0002 => Op {
            name: "ldarg.0",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0003 => Op {
            name: "ldarg.1",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0004 => Op {
            name: "ldarg.2",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0005 => Op {
            name: "ldarg.3",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0006 => Op {
            name: "ldloc.0",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0007 => Op {
            name: "ldloc.1",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0008 => Op {
            name: "ldloc.2",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0009 => Op {
            name: "ldloc.3",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x000a => Op {
            name: "stloc.0",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 0,
        },
        0x000b => Op {
            name: "stloc.1",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 0,
        },
        0x000c => Op {
            name: "stloc.2",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 0,
        },
        0x000d => Op {
            name: "stloc.3",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 0,
        },
        0x000e => Op {
            name: "ldarg.s",
            operand: OperandKind::ShortInlineVar,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x000f => Op {
            name: "ldarga.s",
            operand: OperandKind::ShortInlineVar,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0010 => Op {
            name: "starg.s",
            operand: OperandKind::ShortInlineVar,
            flow: Flow::Next,
            pop: 1,
            push: 0,
        },
        0x0011 => Op {
            name: "ldloc.s",
            operand: OperandKind::ShortInlineVar,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0012 => Op {
            name: "ldloca.s",
            operand: OperandKind::ShortInlineVar,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0013 => Op {
            name: "stloc.s",
            operand: OperandKind::ShortInlineVar,
            flow: Flow::Next,
            pop: 1,
            push: 0,
        },
        0x0014 => Op {
            name: "ldnull",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0015 => Op {
            name: "ldc.i4.m1",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0016 => Op {
            name: "ldc.i4.0",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0017 => Op {
            name: "ldc.i4.1",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0018 => Op {
            name: "ldc.i4.2",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0019 => Op {
            name: "ldc.i4.3",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x001a => Op {
            name: "ldc.i4.4",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x001b => Op {
            name: "ldc.i4.5",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x001c => Op {
            name: "ldc.i4.6",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x001d => Op {
            name: "ldc.i4.7",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x001e => Op {
            name: "ldc.i4.8",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x001f => Op {
            name: "ldc.i4.s",
            operand: OperandKind::ShortInlineI,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0020 => Op {
            name: "ldc.i4",
            operand: OperandKind::InlineI,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0021 => Op {
            name: "ldc.i8",
            operand: OperandKind::InlineI8,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0022 => Op {
            name: "ldc.r4",
            operand: OperandKind::ShortInlineR,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0023 => Op {
            name: "ldc.r8",
            operand: OperandKind::InlineR,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0025 => Op {
            name: "dup",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 2,
        },
        0x0026 => Op {
            name: "pop",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 0,
        },
        0x0027 => Op {
            name: "jmp",
            operand: OperandKind::InlineMethod,
            flow: Flow::Call,
            pop: 0,
            push: 0,
        },
        0x0028 => Op {
            name: "call",
            operand: OperandKind::InlineMethod,
            flow: Flow::Call,
            pop: -1,
            push: -1,
        },
        0x0029 => Op {
            name: "calli",
            operand: OperandKind::InlineSig,
            flow: Flow::Call,
            pop: -1,
            push: -1,
        },
        0x002a => Op {
            name: "ret",
            operand: OperandKind::InlineNone,
            flow: Flow::Return,
            pop: -1,
            push: 0,
        },
        0x002b => Op {
            name: "br.s",
            operand: OperandKind::ShortInlineBrTarget,
            flow: Flow::Branch,
            pop: 0,
            push: 0,
        },
        0x002c => Op {
            name: "brfalse.s",
            operand: OperandKind::ShortInlineBrTarget,
            flow: Flow::CondBranch,
            pop: 1,
            push: 0,
        },
        0x002d => Op {
            name: "brtrue.s",
            operand: OperandKind::ShortInlineBrTarget,
            flow: Flow::CondBranch,
            pop: 1,
            push: 0,
        },
        0x002e => Op {
            name: "beq.s",
            operand: OperandKind::ShortInlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x002f => Op {
            name: "bge.s",
            operand: OperandKind::ShortInlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x0030 => Op {
            name: "bgt.s",
            operand: OperandKind::ShortInlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x0031 => Op {
            name: "ble.s",
            operand: OperandKind::ShortInlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x0032 => Op {
            name: "blt.s",
            operand: OperandKind::ShortInlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x0033 => Op {
            name: "bne.un.s",
            operand: OperandKind::ShortInlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x0034 => Op {
            name: "bge.un.s",
            operand: OperandKind::ShortInlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x0035 => Op {
            name: "bgt.un.s",
            operand: OperandKind::ShortInlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x0036 => Op {
            name: "ble.un.s",
            operand: OperandKind::ShortInlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x0037 => Op {
            name: "blt.un.s",
            operand: OperandKind::ShortInlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x0038 => Op {
            name: "br",
            operand: OperandKind::InlineBrTarget,
            flow: Flow::Branch,
            pop: 0,
            push: 0,
        },
        0x0039 => Op {
            name: "brfalse",
            operand: OperandKind::InlineBrTarget,
            flow: Flow::CondBranch,
            pop: 1,
            push: 0,
        },
        0x003a => Op {
            name: "brtrue",
            operand: OperandKind::InlineBrTarget,
            flow: Flow::CondBranch,
            pop: 1,
            push: 0,
        },
        0x003b => Op {
            name: "beq",
            operand: OperandKind::InlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x003c => Op {
            name: "bge",
            operand: OperandKind::InlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x003d => Op {
            name: "bgt",
            operand: OperandKind::InlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x003e => Op {
            name: "ble",
            operand: OperandKind::InlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x003f => Op {
            name: "blt",
            operand: OperandKind::InlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x0040 => Op {
            name: "bne.un",
            operand: OperandKind::InlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x0041 => Op {
            name: "bge.un",
            operand: OperandKind::InlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x0042 => Op {
            name: "bgt.un",
            operand: OperandKind::InlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x0043 => Op {
            name: "ble.un",
            operand: OperandKind::InlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x0044 => Op {
            name: "blt.un",
            operand: OperandKind::InlineBrTarget,
            flow: Flow::CondBranch,
            pop: 2,
            push: 0,
        },
        0x0045 => Op {
            name: "switch",
            operand: OperandKind::InlineSwitch,
            flow: Flow::CondBranch,
            pop: 1,
            push: 0,
        },
        0x0046 => Op {
            name: "ldind.i1",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0047 => Op {
            name: "ldind.u1",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0048 => Op {
            name: "ldind.i2",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0049 => Op {
            name: "ldind.u2",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x004a => Op {
            name: "ldind.i4",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x004b => Op {
            name: "ldind.u4",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x004c => Op {
            name: "ldind.i8",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x004d => Op {
            name: "ldind.i",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x004e => Op {
            name: "ldind.r4",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x004f => Op {
            name: "ldind.r8",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0050 => Op {
            name: "ldind.ref",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0051 => Op {
            name: "stind.ref",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 0,
        },
        0x0052 => Op {
            name: "stind.i1",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 0,
        },
        0x0053 => Op {
            name: "stind.i2",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 0,
        },
        0x0054 => Op {
            name: "stind.i4",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 0,
        },
        0x0055 => Op {
            name: "stind.i8",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 0,
        },
        0x0056 => Op {
            name: "stind.r4",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 0,
        },
        0x0057 => Op {
            name: "stind.r8",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 0,
        },
        0x0058 => Op {
            name: "add",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x0059 => Op {
            name: "sub",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x005a => Op {
            name: "mul",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x005b => Op {
            name: "div",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x005c => Op {
            name: "div.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x005d => Op {
            name: "rem",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x005e => Op {
            name: "rem.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x005f => Op {
            name: "and",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x0060 => Op {
            name: "or",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x0061 => Op {
            name: "xor",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x0062 => Op {
            name: "shl",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x0063 => Op {
            name: "shr",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x0064 => Op {
            name: "shr.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x0065 => Op {
            name: "neg",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0066 => Op {
            name: "not",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0067 => Op {
            name: "conv.i1",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0068 => Op {
            name: "conv.i2",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0069 => Op {
            name: "conv.i4",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x006a => Op {
            name: "conv.i8",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x006b => Op {
            name: "conv.r4",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x006c => Op {
            name: "conv.r8",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x006d => Op {
            name: "conv.u4",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x006e => Op {
            name: "conv.u8",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x006f => Op {
            name: "callvirt",
            operand: OperandKind::InlineMethod,
            flow: Flow::Call,
            pop: -1,
            push: -1,
        },
        0x0070 => Op {
            name: "cpobj",
            operand: OperandKind::InlineType,
            flow: Flow::Next,
            pop: 2,
            push: 0,
        },
        0x0071 => Op {
            name: "ldobj",
            operand: OperandKind::InlineType,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0072 => Op {
            name: "ldstr",
            operand: OperandKind::InlineString,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0073 => Op {
            name: "newobj",
            operand: OperandKind::InlineMethod,
            flow: Flow::Call,
            pop: -1,
            push: 1,
        },
        0x0074 => Op {
            name: "castclass",
            operand: OperandKind::InlineType,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0075 => Op {
            name: "isinst",
            operand: OperandKind::InlineType,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0076 => Op {
            name: "conv.r.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0079 => Op {
            name: "unbox",
            operand: OperandKind::InlineType,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x007a => Op {
            name: "throw",
            operand: OperandKind::InlineNone,
            flow: Flow::Throw,
            pop: 1,
            push: 0,
        },
        0x007b => Op {
            name: "ldfld",
            operand: OperandKind::InlineField,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x007c => Op {
            name: "ldflda",
            operand: OperandKind::InlineField,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x007d => Op {
            name: "stfld",
            operand: OperandKind::InlineField,
            flow: Flow::Next,
            pop: 2,
            push: 0,
        },
        0x007e => Op {
            name: "ldsfld",
            operand: OperandKind::InlineField,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x007f => Op {
            name: "ldsflda",
            operand: OperandKind::InlineField,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x0080 => Op {
            name: "stsfld",
            operand: OperandKind::InlineField,
            flow: Flow::Next,
            pop: 1,
            push: 0,
        },
        0x0081 => Op {
            name: "stobj",
            operand: OperandKind::InlineType,
            flow: Flow::Next,
            pop: 2,
            push: 0,
        },
        0x0082 => Op {
            name: "conv.ovf.i1.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0083 => Op {
            name: "conv.ovf.i2.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0084 => Op {
            name: "conv.ovf.i4.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0085 => Op {
            name: "conv.ovf.i8.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0086 => Op {
            name: "conv.ovf.u1.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0087 => Op {
            name: "conv.ovf.u2.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0088 => Op {
            name: "conv.ovf.u4.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x0089 => Op {
            name: "conv.ovf.u8.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x008a => Op {
            name: "conv.ovf.i.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x008b => Op {
            name: "conv.ovf.u.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x008c => Op {
            name: "box",
            operand: OperandKind::InlineType,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x008d => Op {
            name: "newarr",
            operand: OperandKind::InlineType,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x008e => Op {
            name: "ldlen",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x008f => Op {
            name: "ldelema",
            operand: OperandKind::InlineType,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x0090 => Op {
            name: "ldelem.i1",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x0091 => Op {
            name: "ldelem.u1",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x0092 => Op {
            name: "ldelem.i2",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x0093 => Op {
            name: "ldelem.u2",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x0094 => Op {
            name: "ldelem.i4",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x0095 => Op {
            name: "ldelem.u4",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x0096 => Op {
            name: "ldelem.i8",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x0097 => Op {
            name: "ldelem.i",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x0098 => Op {
            name: "ldelem.r4",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x0099 => Op {
            name: "ldelem.r8",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x009a => Op {
            name: "ldelem.ref",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x009b => Op {
            name: "stelem.i",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 3,
            push: 0,
        },
        0x009c => Op {
            name: "stelem.i1",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 3,
            push: 0,
        },
        0x009d => Op {
            name: "stelem.i2",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 3,
            push: 0,
        },
        0x009e => Op {
            name: "stelem.i4",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 3,
            push: 0,
        },
        0x009f => Op {
            name: "stelem.i8",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 3,
            push: 0,
        },
        0x00a0 => Op {
            name: "stelem.r4",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 3,
            push: 0,
        },
        0x00a1 => Op {
            name: "stelem.r8",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 3,
            push: 0,
        },
        0x00a2 => Op {
            name: "stelem.ref",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 3,
            push: 0,
        },
        0x00a3 => Op {
            name: "ldelem",
            operand: OperandKind::InlineType,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x00a4 => Op {
            name: "stelem",
            operand: OperandKind::InlineType,
            flow: Flow::Next,
            pop: 3,
            push: 0,
        },
        0x00a5 => Op {
            name: "unbox.any",
            operand: OperandKind::InlineType,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x00b3 => Op {
            name: "conv.ovf.i1",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x00b4 => Op {
            name: "conv.ovf.u1",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x00b5 => Op {
            name: "conv.ovf.i2",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x00b6 => Op {
            name: "conv.ovf.u2",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x00b7 => Op {
            name: "conv.ovf.i4",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x00b8 => Op {
            name: "conv.ovf.u4",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x00b9 => Op {
            name: "conv.ovf.i8",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x00ba => Op {
            name: "conv.ovf.u8",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x00c2 => Op {
            name: "refanyval",
            operand: OperandKind::InlineType,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x00c3 => Op {
            name: "ckfinite",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x00c6 => Op {
            name: "mkrefany",
            operand: OperandKind::InlineType,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x00d0 => Op {
            name: "ldtoken",
            operand: OperandKind::InlineTok,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0x00d1 => Op {
            name: "conv.u2",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x00d2 => Op {
            name: "conv.u1",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x00d3 => Op {
            name: "conv.i",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x00d4 => Op {
            name: "conv.ovf.i",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x00d5 => Op {
            name: "conv.ovf.u",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0x00d6 => Op {
            name: "add.ovf",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x00d7 => Op {
            name: "add.ovf.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x00d8 => Op {
            name: "mul.ovf",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x00d9 => Op {
            name: "mul.ovf.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x00da => Op {
            name: "sub.ovf",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x00db => Op {
            name: "sub.ovf.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0x00dc => Op {
            name: "endfinally",
            operand: OperandKind::InlineNone,
            flow: Flow::Return,
            pop: 0,
            push: 0,
        },
        0x00dd => Op {
            name: "leave",
            operand: OperandKind::InlineBrTarget,
            flow: Flow::Branch,
            pop: 0,
            push: 0,
        },
        0x00de => Op {
            name: "leave.s",
            operand: OperandKind::ShortInlineBrTarget,
            flow: Flow::Branch,
            pop: 0,
            push: 0,
        },
        0x00df => Op {
            name: "stind.i",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 0,
        },
        0x00e0 => Op {
            name: "conv.u",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0xfe00 => Op {
            name: "arglist",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0xfe01 => Op {
            name: "ceq",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0xfe02 => Op {
            name: "cgt",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0xfe03 => Op {
            name: "cgt.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0xfe04 => Op {
            name: "clt",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0xfe05 => Op {
            name: "clt.un",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 2,
            push: 1,
        },
        0xfe06 => Op {
            name: "ldftn",
            operand: OperandKind::InlineMethod,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0xfe07 => Op {
            name: "ldvirtftn",
            operand: OperandKind::InlineMethod,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0xfe09 => Op {
            name: "ldarg",
            operand: OperandKind::InlineVar,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0xfe0a => Op {
            name: "ldarga",
            operand: OperandKind::InlineVar,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0xfe0b => Op {
            name: "starg",
            operand: OperandKind::InlineVar,
            flow: Flow::Next,
            pop: 1,
            push: 0,
        },
        0xfe0c => Op {
            name: "ldloc",
            operand: OperandKind::InlineVar,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0xfe0d => Op {
            name: "ldloca",
            operand: OperandKind::InlineVar,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0xfe0e => Op {
            name: "stloc",
            operand: OperandKind::InlineVar,
            flow: Flow::Next,
            pop: 1,
            push: 0,
        },
        0xfe0f => Op {
            name: "localloc",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0xfe11 => Op {
            name: "endfilter",
            operand: OperandKind::InlineNone,
            flow: Flow::Return,
            pop: 1,
            push: 0,
        },
        0xfe12 => Op {
            name: "unaligned.",
            operand: OperandKind::ShortInlineI,
            flow: Flow::Meta,
            pop: 0,
            push: 0,
        },
        0xfe13 => Op {
            name: "volatile.",
            operand: OperandKind::InlineNone,
            flow: Flow::Meta,
            pop: 0,
            push: 0,
        },
        0xfe14 => Op {
            name: "tail.",
            operand: OperandKind::InlineNone,
            flow: Flow::Meta,
            pop: 0,
            push: 0,
        },
        0xfe15 => Op {
            name: "initobj",
            operand: OperandKind::InlineType,
            flow: Flow::Next,
            pop: 1,
            push: 0,
        },
        0xfe16 => Op {
            name: "constrained.",
            operand: OperandKind::InlineType,
            flow: Flow::Meta,
            pop: 0,
            push: 0,
        },
        0xfe17 => Op {
            name: "cpblk",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 3,
            push: 0,
        },
        0xfe18 => Op {
            name: "initblk",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 3,
            push: 0,
        },
        0xfe1a => Op {
            name: "rethrow",
            operand: OperandKind::InlineNone,
            flow: Flow::Throw,
            pop: 0,
            push: 0,
        },
        0xfe1c => Op {
            name: "sizeof",
            operand: OperandKind::InlineType,
            flow: Flow::Next,
            pop: 0,
            push: 1,
        },
        0xfe1d => Op {
            name: "refanytype",
            operand: OperandKind::InlineNone,
            flow: Flow::Next,
            pop: 1,
            push: 1,
        },
        0xfe1e => Op {
            name: "readonly.",
            operand: OperandKind::InlineNone,
            flow: Flow::Meta,
            pop: 0,
            push: 0,
        },
        _ => return None,
    })
}
