<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><Optimize>true</Optimize><Deterministic>true</Deterministic><AssemblyName>ILens.Patterns</AssemblyName></PropertyGroup>
  <ItemGroup><ProjectReference Include="../Dependency/Dependency.csproj" /><EmbeddedResource Include="message.txt" /></ItemGroup>
</Project>
