[package]
name = "decompiler-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
[dependencies]
clrmeta = "=0.1.0"
goblin = { version = "=0.10.7", default-features = false, features = ["pe32", "pe64", "std"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
